### ISSUE TITLE
Could we add the SIG hosts as moderators to this repo?

### ISSUE THREAD

**Issue by evanwolf** [decentralized-identity/SIG-IoT#7]
Damian Glover and Lubna Dajani.

**Comment by paulgrehan** [comment]
Damian has (we have a Team for maintainer rights) - I don't have a Github handle for Lubna as yet ?

**Comment by LubnaDajani** [comment]
hello thank you for pinging me on this Phil hello Paul

**Comment by LubnaDajani** [comment]
I am totally new to using Github and need to find my way around. thank you for any and all help

**Comment by evanwolf** [comment]
Damian and Lubna seem to be moderators now. Thanks!
